language: node_js
sudo: false

install:
  - npm install

cache:
  directories:
    - "node_modules"

node_js:
  - "9"
  - "8"
  - "7"
  - "6"

script:
  - npm test

after_success:
  - "npm install coveralls@3 && nyc report --reporter=text-lcov | coveralls"